services:
  api:
    container_name: labs-companies-api
    image: companies-api
    build:
      context: .
      dockerfile: src/Companies.Api/Dockerfile
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTIONSTRINGS__POSTGRES=Host=postgres;Database=Companies;Username=postgres;Password=postgres
      - RABBITMQ__HOST=rabbitmq
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  import-worker:
    container_name: labs-companies-import-worker
    image: companies-import-worker
    build:
      context: .
      dockerfile: src/Companies.Import.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRINGS__POSTGRES=Host=postgres;Database=Companies;Username=postgres;Password=postgres
      - RABBITMQ__HOST=rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    container_name: labs-companies-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-Companies}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    container_name: labs-companies-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
